### ISSUE TITLE
Palabras de origen múltiple

### ISSUE THREAD

**Issue by cosmoscalibur** [angelcarmona/pyrae#1]
Palabras de origen múltiple no presentan forma para obtener su significado.  
Ejemplo:  

    >import pyrae
    >pyrae.DLE().exact("chucho")
    [['chucho1, cha.; chucho2.; chucho3.; chucho4.; chucho5.','91vbETk|91xUs44|91z9AnY|920u7uV|924A8Os']]

Acorde a la presentación en el README no creo que esta sea la intención durante su uso.

**Comment by angelcarmona** [comment]
¡Muchas gracias por tu aportación!

Lo he corregido, ahora al buscar este tipo de palabras se devolverá una lista donde cada elemento es una lista que contiene el lema y el id de cada uno de los resultados. Ejemplo:

`>>> pyrae.DLE.exact('chucho')
[['chucho1, cha.', '91vbETk'], ['chucho2.', '91xUs44'], ['chucho3.', '91z9AnY'], ['chucho4.', '920u7uV'], ['chucho5.', '924A8Os']]
`

**Comment by cosmoscalibur** [comment]
Gracias @angelcarmona , sin embargo, en ese caso no me queda claro cual es la intención del método `exact`. Con unas palabras mostrará el significado mientras que con otras mostrará identificadores (finalmente, lo mismo pasaba antes, con la ventaja de que el identificador múltiple permitía usar `fetch` para tener los significados completos).  
¿Me puedes aclarar por favor la intención del método `exact`?.

**Comment by angelcarmona** [comment]
@cosmoscalibur, tengo que hacer la documentación de este módulo, será lo siguiente que haga.

El método exact debería ser similar a hacer una búsqueda por lemas "exacta" en la web de la RAE. Ejemplos:

- Si en la web haces una búsqueda por palabras de "casa", los resultados son "casa" y "casar", este último con dos artículos, y tienes que seleccionar el resultado que te interese para ver su definición. Si haces una búsqueda exacta el resultado es "casa", y ves su definición directamente.

- Si en la web haces una búsqueda por palabras de "chucho", los resultados son "chuchar" y "chucho", este último con cinco artículos, y tienes que seleccionar el resultado que te interese para ver su definición. Si haces una búsqueda exacta, el resultado es "chucho", con cinco artículos, y tienes que seleccionar el resultado que te interese para ver su definición.

Los resultados en los ejemplos que he puesto son los mismos en la web de la RAE y en PyRAE. Ahora mismo:

- Si el resultado contiene un único artículo, se devuelve una lista [definición, id_verbo], donde id_verbo es el id si la palabra buscada es un verbo, o None en caso contrario.

-Si el resultado contiene varios artículos, se devuelve una lista donde cada uno de sus elementos es una lista [palabra, id_palabra]. En este caso id_palabra nunca será None.

Esto puede ser un poco confuso, voy a documentar correctamente el código y a unificar los resultados de cada uno de los métodos.

Estoy abierto a todo tipo de comentarios sobre el módulo y su forma de utilizarlo, colaboraciones, etc.

¡Muchas gracias una vez más!

**Comment by cosmoscalibur** [comment]
Gracias por la aclaración
