### ISSUE TITLE
Conjugación de verbos devuelve None

### ISSUE THREAD

**Issue by cosmoscalibur** [angelcarmona/pyrae#2]
Estuve probando la conjugación de verbos, y con todos los probados (incluso con [amar] que es verbo modelo de conjugación), obtengo como resultado `None`.  

    >import pyrae
    >print(pyrae.DLE().conjugate_verb("amar"))
    None

**Comment by angelcarmona** [comment]
Corregido. Hay que darle un mejor formato a la lista resultado.
